#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
#
# ✅ VERIFIED (2026-07-31): runs on first boot, seeds the test user, and Apache
# comes up serving the gpoddersync API. See docs/journal.adoc.
#
# Writes opodsync's config on first boot and seeds the test user, so integration
# tests get working credentials without a human clicking through /register.php.
set -euo pipefail

# opodsync resolves both DATA_ROOT and its own config file relative to the webroot
# (server/_inc.php: `$cfg_file = (getenv('DATA_ROOT') ?: ROOT . '/data') . '/config.local.php'`),
# so the config has to live inside the mounted volume, not next to index.php.
DATA_DIR=/var/www/html/data
CONFIG="$DATA_DIR/config.local.php"

mkdir -p "$DATA_DIR"

if [[ ! -f "$CONFIG" ]]; then
    # The `namespace OPodSync;` line is load-bearing. _inc.php looks for
    # `OPodSync\ENABLE_SUBSCRIPTIONS` and friends; constants defined at global scope
    # are silently ignored and every setting quietly falls back to its default.
    cat > "$CONFIG" <<PHP
<?php
// Generated by opodsync-entrypoint.sh on first boot.

namespace OPodSync;

// Open registration, so a disposable server can be reseeded without an admin flow.
// Fine for a throwaway test container; never do this on anything reachable.
const ENABLE_SUBSCRIPTIONS = true;

// The seeding step runs under PHP-CLI, where opodsync cannot infer a URL from
// \$_SERVER. Setting it explicitly also keeps the web UI's own links correct.
const BASE_URL = 'http://localhost:${OPODSYNC_PORT:-8080}/';

const TITLE = 'Podsilo test server (disposable)';
PHP
fi

chown -R www-data:www-data "$DATA_DIR"

# Seed the first user through opodsync's OWN GPodder::subscribe(), which does the
# password hashing (password_hash/PASSWORD_DEFAULT) and username validation. Poking
# rows into SQLite ourselves would mean reimplementing that — exactly the guessing
# CLAUDE.md §3 warns against. Runs as www-data so the SQLite file it creates stays
# writable by Apache. Idempotent: a restart hits "Username already exists", which is
# treated as success.
if [[ -n "${OPODSYNC_USER:-}" && -n "${OPODSYNC_PASSWORD:-}" ]]; then
    cat > /tmp/opodsync-seed.php <<'PHP'
<?php
namespace OPodSync;

// _inc.php reads these to derive BASE_URL; under CLI there is no request to read.
$_SERVER['SERVER_NAME'] ??= 'localhost';
$_SERVER['SERVER_PORT'] ??= 80;
$_SERVER['REQUEST_URI'] ??= '/';

require '/var/www/html/_inc.php';

$user = getenv('OPODSYNC_USER');
$error = $gpodder->subscribe($user, getenv('OPODSYNC_PASSWORD'));

if ($error === null) {
    fwrite(STDERR, "opodsync: created user '$user'\n");
} elseif (str_contains($error, 'already exists')) {
    fwrite(STDERR, "opodsync: user '$user' already exists, leaving it alone\n");
} else {
    fwrite(STDERR, "opodsync: could not create user '$user': $error\n");
    exit(1);
}
PHP
    chmod 0644 /tmp/opodsync-seed.php
    su www-data -s /bin/sh -c "php /tmp/opodsync-seed.php" \
        || echo "opodsync: user seeding failed — register manually at /register.php"
    rm -f /tmp/opodsync-seed.php
fi

echo "opodsync ready (user '${OPODSYNC_USER:-podsilo}')"

exec "$@"
